import { Inter } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/nav/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gamba: Go Big or Go Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className + ` bg-black min-h-screen h-fit text-white flex flex-col justify-between`}>
        <Navbar />
        <div className="max-w-screen-xl mx-auto w-11/12 xl:w-full p-4 mb-8">{children}</div>
      </body>
    </html>
  );
}
