import { Inter } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import AuthProvider from "@/components/auth/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gamba: Go Big or Go Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className + ` bg-black min-h-screen mx-auto h-fit text-white flex flex-col justify-between`}>
        <AuthProvider>
          <Navbar />
          <div className="max-w-screen-xl mx-auto w-full mt-16 mb-8 xl:w-full py-4 px-4 sm:px-8 text-white">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
